### ISSUE TITLE
Cayley transformation degeneracy

### ISSUE THREAD

**Issue by sweeneychris** [manhofer/Line3Dpp#1]
When the matrix Q in the Plucker-to-Cayley transformation is symmetric, the transformation is not defined. https://github.com/manhofer/Line3Dpp/blob/master/optimization.cc#L56

For instance, when using 3D endpoints (5, -5, -5) and (-5, -5, -5) the matrix Q is symmetric and s will be filled with NaNs. Do you have any thoughts on how to avoid this? 

Obviously you can simply rotate the entire model so that the 3D line does not produce this degeneracy but it is often the case that you take images with front-parallel planes (which would produce lines parallel or nearly parallel to the x-axis) so this degeneracy could happen naturally.

**Comment by manhofer** [comment]
Hi

Thx for pointing this out! I was not aware of that problem.

I am not yet sure if there is an elegant solution around this, but for the moment I changed the code such that in these rare cases the line is just not bundled, and the line parameters are just kept as they were before. Since the bundling does not change the result by a large margin (for the general case), this is probably a solution one could live with. However, maybe there is a different way to avoid this problem. I will look into that when I have time.

Manuel
