### ISSUE TITLE
how to update orthogonal weigh matrix by cayley transformation 

### ISSUE THREAD

**Issue by NinaLLI** [manhofer/Line3Dpp#11]
I want to update orthogonal  weight matrix by Cayley transformation because weight matrix must preserve orthogonality , first I decompose Wight matrix to U,S,V and update U,V separately by using Cayley transformation what about s , How can I update it ? should update S by typical gradient descent ? after  theses three component get update I want to composes them  like W= U*S*V  in order to have  updated W

**Comment by manhofer** [comment]
Hi. In my code, I use the Cayley representation only in context with the ceres-solver. That means that I give the values to ceres, compute the residual functions, and let the solver do the rest. Since I am not an expert in optimization, I don't really know what ceres does with the values or how it updates them.
