### ISSUE TITLE
any suggestions for reconstructing details

### ISSUE THREAD

**Issue by tangeroo** [manhofer/Line3Dpp#22]
Hi, 
  Thanks for your excellent work. I tested this project using the openmvg input. Here is my 3D result:
![image](https://user-images.githubusercontent.com/25971461/93289887-0f6b2000-f812-11ea-952d-ad4a9bae9001.png)
as you can see the red marked parts, there are some details of windows lost. However, I find my window edges in these parts exist(see following). Do you know why this happened or any suggestions for me to reconstruct the details.
![image](https://user-images.githubusercontent.com/25971461/93290177-b9e34300-f812-11ea-989d-60e99fb838c4.png)
![image](https://user-images.githubusercontent.com/25971461/93290213-cebfd680-f812-11ea-9dca-3e9f58495fa6.png)
![image](https://user-images.githubusercontent.com/25971461/93290236-e0a17980-f812-11ea-819f-275b2ab47669.png)
![image](https://user-images.githubusercontent.com/25971461/93290262-ebf4a500-f812-11ea-978e-d4a7f29ad02c.png)
  Thank you in advance.

**Comment by manhofer** [comment]
Hi

From the reconstruction result above we can see that **horizontal** lines are mostly missing, while **vertical** lines are reconstructed quite well. This is expected to happen when the direction of the camera motion is (sort of) parallel to the vertical lines, i.e. when you move around the building on foot (as it seems to be the case here, am I right?).

This happens because of the epipolar guided weak matching strategy, which struggles to produce proper matches in this case. The reason is that the epipolar lines of the endpoints of a given line segment in one image are almost identical in the matching candidate image, and hence intersecting them with the correct matching line (which is also almost parallel to the epipolar lines) does not really work. So correct matches for horizontal lines are rare, and they are not reconstructed well.

The only way to solve this issue with my algorithm is to add also vertical camera motion to the image set (e.g. by using a camera drone). Other than that, one could try to switch from an appearance-less epipolar-guided matching to an appearance based matching using line descriptors or something, but this is not built into Line3D++.

Hope I could shed some light on this issue!

Best,
Manuel

**Comment by tangeroo** [comment]
Yes, indeed the camera motion is parallel to the horizontal lines. Thank you for your explanation and I do understand it. I'll try to see if I can use some line descriptors here.
