### ISSUE TITLE
STL files show nothing  of the result

### ISSUE THREAD

**Issue by EthanGreen75** [manhofer/Line3Dpp#4]
Hi,@manhofer
I build all the procedures in VS2013.
Finally, three files were generated but when I open the STL with any STL viewer, nothing show up. OBJ file seems work well and i can see the point clouds. I guess the every pair of points stands for one line in 3D space, is that right?
Could you tell me what software you are using for openning the STL file?

**Comment by EthanGreen75** [comment]
By the way, i use the software ABViewer to open STL file, nothing shows. But when i use the preview function of ABViewer i can see a 2D picture of the 3D structure. It's really strange could you give me some hints?
![image](https://cloud.githubusercontent.com/assets/5960871/15490710/215b6040-219d-11e6-8c5f-9678a20a18ef.png)

![image](https://cloud.githubusercontent.com/assets/5960871/15490715/341d2556-219d-11e6-9593-92648c5b6ce0.png)

**Comment by manhofer** [comment]
Am 24.05.2016 um 04:49 schrieb Ethan Green:
>
> By the way, i use the software ABViewer to open STL file, nothing 
> shows. But when i use the preview function of ABViewer i can see a 2D 
> picture of the 3D structure. It's really strange could you give me 
> some hints?
> image 
> <https://cloud.githubusercontent.com/assets/5960871/15490710/215b6040-219d-11e6-8c5f-9678a20a18ef.png>
>
> image 
> <https://cloud.githubusercontent.com/assets/5960871/15490715/341d2556-219d-11e6-9593-92648c5b6ce0.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/manhofer/Line3Dpp/issues/4#issuecomment-221152939>
>

Hi

The .stl files are more or less just a workaround, and represent the 3D 
lines as triangles where two of the endpoints are identical. I have used 
this representation because it was also done this way in the paper by 
Jain et al. from CVPR 2010 [1], which was the motivation for my 
approach. This means that some viewers might cancel out the 3D lines, 
since the underlying triangles have a zero area.

I am always using the freeware tool Meshlab to open the .stl files (see 
Readme file).

I will look into the possibility of changing the way the 3D lines are 
represented in the .stl files, as real lines rather than "fake" triangles.

Best,
Manuel

[1]: http://resources.mpi-inf.mpg.de/LineReconstruction/

-- 
Dipl.-Ing. Manuel Hofer
Schanzelgasse 24/23
A-8010 Graz

**Comment by EthanGreen75** [comment]
@manhofer ，
Thank you so much for your reply so quickly. It really helps me a lot.

**Comment by manhofer** [comment]
You're welcome :-)

**Comment by manhofer** [comment]
I will close this issue for now. If I change the stl representation I will let you know.
